# Generated by Django 4.2.9 on 2024-02-05 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Pro_brand',
            field=models.CharField(default='Paws', max_length=80),
        ),
        migrations.AddField(
            model_name='product',
            name='Pro_image',
            field=models.ImageField(default='', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='product',
            name='Pro_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='Pro_desc',
            field=models.TextField(default='Write Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Pro_name',
            field=models.CharField(default='productName', max_length=50),
        ),
    ]
