# Generated by Django 3.1.7 on 2024-02-19 07:31

import autoslug.fields
from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_pro_brand_product_pro_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=15)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='category_name')),
            ],
        ),
        migrations.AlterModelManagers(
            name='product',
            managers=[
                ('pm', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
